### ISSUE TITLE
Error occurred while enabling FactionsAlias v1.3.1 (Is it up to date?)

### ISSUE THREAD

**Issue by ghost** [MarkehMe/FactionsAlias#3]
Hey

Getting this error http://paste.yu8.me/?eee6ddefbea4ce55#ggD/qnkGSqu0T1cNe7g3kROo/DV5zscL2mGQKdgdd08=

**Comment by markhughes** [comment]
Thanks for reporting this! What version of Factions and MassiveCore do you have?

**Comment by markhughes** [comment]
Notice you're using PerWorld plugin.. can you disable this for FactionsAlias? 

I'm not sure it will work very well.. either way, it will just hook directly into Factions so you can enable it for Factions but not FactionsAlias (if it works with Factions).

Can you let me know if that works?

**Comment by ghost** [comment]
The latest versions of Factions and MassiveCore.

I need the PerWorld as I do not want the Alias to make a mess on other worlds set up (:

Sorry for the long respond time.

**Comment by markhughes** [comment]
I don't understand how that will work, FactionsAlias should not be enabled on PerWorld as it is an extension of Factions.

**Comment by ghost** [comment]
Indeed, that was why I got confused also.

**Comment by markhughes** [comment]
So does removing FactionsAlias from the PerWorld configuration fix the issue?
